import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";

export function ChatEmptyState() {
  return (
    <div className="flex min-h-[40vh] flex-col items-center justify-center px-2">
      <Card className="w-full max-w-md border-dashed border-border/80 bg-muted/20 shadow-none">
        <CardHeader className="text-center">
          <CardTitle className="text-lg font-medium">New conversation</CardTitle>
          <CardDescription className="text-balance">
            Ask a question below. Responses are generated by an external model; do not paste secrets or
            regulated personal data.
          </CardDescription>
        </CardHeader>
        <CardContent className="flex justify-center pb-6">
          <div className="h-1 w-12 rounded-full bg-muted-foreground/25" aria-hidden />
        </CardContent>
      </Card>
    </div>
  );
}
